# Theme config
themesDir = "./themes/"
theme = "hugo-theme-codex"

# Override these settings with your own
title = "Cy | Space"
languageCode = "en-us"
baseURL = "https://cybarspace.github.io"
copyright = "© {2021}"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-163428122-1"

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/DrCyco"
  github = "https://github.com/cybarspace"
  email = "mailto:sksaad@tutanota.com"
  facebook = "https://facebook.com/sksaad47"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/cybarnaut"
  linkedin = "https://www.linkedin.com/in/sk-saad"
  youtube = "https://www.youtube.com/channel/UCA6pL90nzUonUJLyefRUO4w"

  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported:
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Email", "Facebook", "Instagram", "LinkedIn", "YouTube"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

