# Theme config
themesDir = "./themes/"
theme = "hugo-theme-codex"

# Override these settings with your own
title = "Cybarspace | A home for my thoughts"
languageCode = "en-us"
baseURL = "https://www.cybarspace.dev"
copyright = "Sheikh Saad © 2021"

# Add your Disqus shortname here.
disqusShortname = "cybarspace"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "UA-187828184-2"

# Optional params
[params]
  # Open Graph
  description = "Here, I discuss code, my life and things that pique my interest"
  images = ["https://user-images.githubusercontent.com/50134239/110678729-d5973700-8200-11eb-9b92-da88f58f37af.png"]

  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/cybardev"
  github = "https://github.com/cybardev"
  email = "mailto:sheikh@cybar.dev"
  #facebook = "https://facebook.com/cybardev"
  # gitlab = "https://gitlab.com/<your handle>"
  #instagram = "https://instagram.com/cybardev"
  linkedin = "https://www.linkedin.com/in/cybardev"
  #youtube = "https://www.youtube.com/channel/UCA6pL90nzUonUJLyefRUO4w"

  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported:
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Email", "LinkedIn", "GitHub", "Twitter"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = "portfolio"
  name = "portfolio"
  title = "Portfolio"
  url = "https://sheikh.cybar.dev"

